### ISSUE TITLE
[Header] 建议将头部的移动端自适应统一放在Header组件中处理

### ISSUE THREAD

**Issue by Lakphy** [mld-njupt/qingyou-website#17]
建议将头部的移动端自适应统一放在Header组件中处理

**Comment by mld-njupt** [comment]
这是出于什么角度呢，个人觉得没必要dom结构完全不同，实现方案也不太一样。分离是否方便后期的维护

**Comment by mld-njupt** [comment]
> 建议将头部的移动端自适应统一放在Header组件中处理

这是出于什么角度呢，个人觉得没必要dom结构完全不同，实现方案也不太一样。分离是否方便后期的维护？

**Comment by MaxtuneLee** [comment]
统一不太好维护，不同页面的Header要求不一样（

**Comment by Lakphy** [comment]
> 统一不太好维护，不同页面的Header要求不一样（

要求不一样那不是问题更大（，基本风格都不能统一

**Comment by Lakphy** [comment]
我觉得不应该在每一个页面中单独判断渲染哪个Header组件，至少应该放在一个Header代码中，在Header中判断渲染哪个

**Comment by MaxtuneLee** [comment]
这个确实
